export const LOAD_SUMMARY_SUCCESS = 'LOAD_SUMMARY_SUCCESS';
export const SUBMIT_BET_REQUEST = 'SUBMIT_BET_REQUEST';
export const SUBMIT_BET_SUCCESS = 'SUBMIT_BET_SUCCESS';
export const SUBMIT_BET_ERROR = 'SUBMIT_BET_ERROR';