export const DATA_LOAD_SUCCESS = "DATA_LOAD_SUCCESS";
export const SAVE_MY_DATA = "SAVE_MY_DATA";
export const LOAD_PROJECTS_REQUEST = 'LOAD_PROJECTS_REQUEST';
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';